// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CompositionService is the Wails-facing layer over the composition
 * domain package -- it holds no domain logic of its own (that's
 * internal/domain/composition), only the state and persistence a
 * stateless package can't own: user-composed workflows, mirroring
 * TriggerService's own shape (triggerservice.go) rather than inventing a
 * new one. See docs/SPEC.md §3's `UX: PROTOTYPE` entry for what this is
 * testing.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as markdown$0 from "../../adapters/markdown/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as aiprovider$0 from "../../domain/aiprovider/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as composition$0 from "../../domain/composition/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CapabilityMap exposes docs/SPEC.md §3.3's capability map as real Go
 * data, not parsed docs -- composition's own sub-capabilities (Trigger,
 * Decision, Parallel Steps, ...), one level down from the page-level
 * CapabilitiesService.List(). The in-app Spec view that used to render
 * this was retired; docs/SPEC.md §3.3 remains the source of truth.
 */
export function CapabilityMap(): $CancellablePromise<composition$0.MapEntry[] | null> {
    return $Call.ByID(1178766968);
}

/**
 * ConfirmClipboardApply re-parses jsonData and applies it. Kind-sniffs
 * and validates the payload shape itself (clipboard-specific error
 * messages), then delegates the actual create-vs-update decision to
 * ImportWorkflow -- ADR-0036 decision 3's uniform id rule, so this and
 * every other workflow import entry point (file picker, MCP) share
 * exactly one implementation of it.
 */
export function ConfirmClipboardApply(jsonData: string): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(215205686, jsonData);
}

/**
 * ConversionRuleSets lists the switchable rule sets a conversion
 * profile can turn on -- the profile page's check boxes.
 */
export function ConversionRuleSets(): $CancellablePromise<markdown$0.RuleSet[] | null> {
    return $Call.ByID(245187735);
}

/**
 * CreateWorkflow composes and configures a new workflow in one step, per
 * SPEC.md §3: ResolveNodeDefaults validates every node's type and fills
 * in any missing config with that field's default, so the stored
 * workflow is never partially configured. The graph shape itself (does
 * it form one valid chain?) isn't re-checked here -- ExecuteWorkflow
 * validates that at run time, and the canvas is separately designed to
 * prevent drawing an invalid graph in the first place.
 */
export function CreateWorkflow(label: string, description: string, nodes: composition$0.Node[] | null, edges: composition$0.Edge[] | null): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(3001581041, label, description, nodes, edges);
}

/**
 * DeleteWorkflow removes a workflow -- seeded or user-composed, both
 * live in c.user (see Workflows' doc comment), no built-in special
 * case. Blocked while any OTHER workflow's child-workflow node still
 * references id (docs/adr/0040 decision 3, same reference-integrity
 * rule ConfigureService's own Delete* methods apply to every other
 * RefKind, via WorkflowsReferencing).
 */
export function DeleteWorkflow(id: string): $CancellablePromise<void> {
    return $Call.ByID(4072179394, id);
}

/**
 * ExportWorkflow serializes id's current definition as an indented,
 * portable JSON string -- share it, commit it to git, or import it into
 * another Mill instance. Read-only: never mutates c.user, never touches
 * the settings store.
 */
export function ExportWorkflow(id: string): $CancellablePromise<string> {
    return $Call.ByID(861882823, id);
}

/**
 * ImportWorkflow parses jsonData (ExportWorkflow's own output, or a
 * hand-authored file in the same shape) and applies ADR-0036 decision
 * 3's uniform import rule: no id -> create fresh (delegates to
 * CreateWorkflow, held to exactly the same validation bar as a
 * hand-composed workflow, no import-specific leniency); an id unknown
 * here -> create preserving that id; an id matching a local workflow ->
 * update through the same snapshot-then-replace chokepoint MCP's
 * update_workflow tool uses. Attributes/Notes apply as a second step
 * (applyImportedExtras) on the create paths, matching the existing
 * compose-then-configure flow every hand-composed workflow already
 * goes through (Configure's Attributes tab, the canvas's own notes).
 */
export function ImportWorkflow(jsonData: string): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(1581677120, jsonData);
}

export function NodeTypes(): $CancellablePromise<composition$0.NodeType[] | null> {
    return $Call.ByID(1317568469);
}

/**
 * PrepareAIProviderFeatureSample prepares or reopens the one ordinary sample
 * workflow associated with this provider and operation. It never runs it.
 */
export function PrepareAIProviderFeatureSample(providerID: string, operation: aiprovider$0.Operation): $CancellablePromise<aiprovider$0.SamplePreview> {
    return $Call.ByID(1144755608, providerID, operation);
}

/**
 * PreviewClipboardApply parses jsonData (clipboard contents) and reports
 * what ConfirmClipboardApply would do WITHOUT persisting anything --
 * docs/goals/0039's preview-confirm model. See ClipboardApplyPreview's
 * own doc comment for why malformed/unrecognized input is a value, not
 * an error.
 */
export function PreviewClipboardApply(jsonData: string): $CancellablePromise<$models.ClipboardApplyPreview> {
    return $Call.ByID(3204913770, jsonData);
}

/**
 * PreviewConversion converts html with exactly the given rule sets --
 * the profile page's side-by-side sample (goal 0305 slice 6): one call
 * per profile, the same converter a run uses.
 */
export function PreviewConversion(html: string, ruleSets: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(5780220, html, ruleSets);
}

/**
 * PreviewConversionWithProfile converts through a profile by id
 * (empty: every rule set) -- what the converter step does.
 */
export function PreviewConversionWithProfile(html: string, profileID: string): $CancellablePromise<string> {
    return $Call.ByID(643203713, html, profileID);
}

/**
 * PreviewHTMLToMarkdown converts html through the same converter
 * process-html-to-markdown's node execution uses with no profile
 * chosen (every rule set), so a preview always matches what a real run
 * would produce. Empty input returns empty without invoking the
 * converter -- there's nothing to preview.
 */
export function PreviewHTMLToMarkdown(html: string): $CancellablePromise<string> {
    return $Call.ByID(600847809, html);
}

/**
 * PublishExistingVersion moves the live pointer to an already-captured
 * snapshot -- rollback (or roll-forward) without mutating anything.
 */
export function PublishExistingVersion(id: string, version: number): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(2999870746, id, version);
}

/**
 * PublishWorkflow snapshots the draft head as the next version and
 * makes it live (publish == live, one concept -- ADR-0021).
 */
export function PublishWorkflow(id: string): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(3303245778, id);
}

/**
 * ReadHostClipboardText reads the OS pasteboard's plain-text flavor via
 * the clipboard adapter (goal 0229) -- the door the Quick Panel's "Apply
 * from clipboard..." row calls instead of navigator.clipboard.readText,
 * which throws a permission error inside the panel's own auxiliary
 * WKWebView (no permission model applies to a Go-side pasteboard read).
 */
export function ReadHostClipboardText(): $CancellablePromise<string> {
    return $Call.ByID(1976418567);
}

/**
 * ResetWorkflowToSeed replaces id's content with the current golden's
 * (docs/goals/0037 item 4) -- a new published version, non-destructive
 * (the prior history stays in Versions, reachable via the existing
 * rollback UI), and clears the Modified latch. Deliberately its own
 * method, not routed through mutateWorkflow: mutateWorkflow's own
 * choke point (below) unconditionally re-latches Modified on every
 * call, which would immediately undo the very reset this performs.
 */
export function ResetWorkflowToSeed(id: string): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(3221719814, id);
}

/**
 * RestorableWorkflows returns every built-in workflow the user
 * deliberately deleted (tombstoned) and not since restored -- the read
 * model for a "Restore example…" affordance (docs/goals/0037 item 5),
 * shown only when non-empty.
 */
export function RestorableWorkflows(): $CancellablePromise<composition$0.Workflow[] | null> {
    return $Call.ByID(2845480415);
}

/**
 * RestoreAIProviderFeatureSample explicitly restores a modified sample's
 * saved definition while preserving its workflow identity and lifecycle.
 */
export function RestoreAIProviderFeatureSample(providerID: string, operation: aiprovider$0.Operation): $CancellablePromise<aiprovider$0.SamplePreview> {
    return $Call.ByID(4160332279, providerID, operation);
}

/**
 * RestoreVersionToDraft copies a snapshot's definition back into the
 * editable head -- the "load an old version into the editor" half of
 * rollback; publishing it afterward is a separate, explicit act.
 */
export function RestoreVersionToDraft(id: string, version: number): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(1369969118, id, version);
}

/**
 * RestoreWorkflow un-tombstones id and re-seeds it at the current
 * golden's content -- the reverse of DeleteWorkflow for a built-in
 * (docs/goals/0037 item 5).
 */
export function RestoreWorkflow(id: string): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(3075661923, id);
}

/**
 * SeedRevisions returns the CURRENTLY SHIPPED revision of every golden
 * workflow, keyed by ID -- lets the frontend's reset affordance render
 * an accurate "Reset to shipped example vN" (docs/goals/0037 item 4)
 * without guessing: a Modified workflow's own Seed.SeedRevision freezes
 * at whatever it was when the latch fired, which can drift behind the
 * code's current golden if a later Mill release bumps it further.
 */
export function SeedRevisions(): $CancellablePromise<{ [_ in string]?: number } | null> {
    return $Call.ByID(3687732097);
}

/**
 * SetWorkflowDefaultEnvironment declares (or clears, with
 * environmentID "") the Environment this workflow's runs use unless a
 * run picks another (goal 0306 S5, Workflow.DefaultEnvironmentID's own
 * doc comment). A dedicated setter rather than a wider UpdateWorkflow
 * signature, for the same reason SetWorkflowOffer is one: this is
 * workflow metadata edited independently of the graph, routed through
 * the mutateWorkflow choke point.
 */
export function SetWorkflowDefaultEnvironment(workflowID: string, environmentID: string): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(598845571, workflowID, environmentID);
}

/**
 * SetWorkflowDisabled flips the inactive state (ADR-0021: disabling
 * pauses production -- triggers and child calls -- while test runs
 * stay allowed, n8n's own semantics).
 */
export function SetWorkflowDisabled(id: string, disabled: boolean): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(2431241325, id, disabled);
}

/**
 * SetWorkflowOffer declares (or clears, with requestID "") the
 * Integration whose recognized cards offer this workflow as an action
 * (goal 0126, Workflow.OfferOnRequestID's own doc comment). A
 * dedicated setter rather than a wider UpdateWorkflow signature: the
 * offer is workflow metadata edited independently of the graph, routed
 * through the mutateWorkflow choke point (UpdatedAt/Seed.Touch/
 * persist/emit all inherited).
 */
export function SetWorkflowOffer(workflowID: string, requestID: string): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(3085845381, workflowID, requestID);
}

/**
 * SnapshotDraft captures id's current draft head as a new immutable
 * version WITHOUT publishing it -- the auto-snapshot-before-write
 * safety net for MCP-driven authoring (docs/adr/0025): anything an
 * external LLM changes is one "load into draft" away from undone,
 * which is a stronger guarantee than forbidding updates ever was.
 */
export function SnapshotDraft(id: string): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(551683575, id);
}

/**
 * UpdateAttributes replaces a workflow's declared Attributes schema in
 * place -- the delegate ConfigureService (configureservice.go) calls for
 * its Attributes CRUD, per SPEC.md §3.5's "Configure-authored but
 * workflow-scoped" cardinality (Attributes aren't their own top-level
 * entity the way an HTTPRequest/List is, they're metadata on a Workflow).
 * Re-validates the existing Nodes/Edges against the *new* schema before
 * accepting it: a Decision edge referencing a field this change removes
 * or retypes must be caught here, not left to silently break the next
 * time that workflow runs.
 */
export function UpdateAttributes(workflowID: string, attrs: composition$0.AttributeDef[] | null): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(4294844568, workflowID, attrs);
}

/**
 * UpdateNotes replaces a workflow's canvas Notes in place -- the same
 * shape as UpdateAttributes (compositionservice.go) already established
 * for a workflow-scoped collection saved independently of Nodes/Edges,
 * since a note is authoring-space annotation, not a step (docs/goals/0055).
 * No graph re-validation is needed: Notes carry no reference
 * ValidateGraph could ever break. Split into its own file per the
 * 500-line convention (.claude/rules/architecture.md), the same
 * per-concern split compositionservice_versioning.go/
 * compositionservice_export.go already follow.
 */
export function UpdateNotes(workflowID: string, notes: composition$0.Note[] | null): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(3223557182, workflowID, notes);
}

/**
 * UpdateWorkflow replaces an existing user-composed workflow's nodes/
 * edges (and label/description) in place, keeping its ID stable -- so
 * re-opening a saved workflow on the canvas and saving edits updates it
 * rather than creating a duplicate. Every workflow (seeded or
 * user-composed) lives in c.user (see Workflows' doc comment), so this
 * works uniformly on both -- no built-in special case.
 */
export function UpdateWorkflow(id: string, label: string, description: string, nodes: composition$0.Node[] | null, edges: composition$0.Edge[] | null): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(3901352244, id, label, description, nodes, edges);
}

/**
 * UpdateWorkflowFromExport replaces id's draft head with an
 * exported-workflow JSON definition -- the same wire shape
 * ExportWorkflow produces and ImportWorkflow consumes, reused as the
 * update protocol so there is exactly one document format
 * (docs/adr/0025). Validation is UpdateWorkflow's own (ValidateGraph,
 * ResolveNodeDefaults); attributes/notes update alongside when the
 * field is explicitly present (nil means "the source document never
 * declared this field," not "clear it" -- an older export with no
 * "notes" key must never wipe an existing workflow's notes).
 */
export function UpdateWorkflowFromExport(id: string, jsonData: string): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(1077414218, id, jsonData);
}

/**
 * ValidateDraft runs composition.ValidateGraph against not-yet-saved
 * canvas state -- the editor's own authoring-validation surface
 * (docs/adr/0028), called on a debounce after every nodes/edges/config
 * change so the toolbar badge and issues panel show every outstanding
 * problem (warnings included), not just the first thing a real Save
 * attempt would eventually reject on. Resolves node defaults first
 * (deriving Kind server-side, same as Create/Update) so a still-
 * drafting node's derived Kind can't drift from what a real save would
 * compute; an unresolvable node type (e.g. mid node-type-swap, before
 * the draft would ever be trusted for a real save) surfaces as a single
 * Error issue instead of a raw RPC failure, so the panel always has
 * something coherent to render.
 */
export function ValidateDraft(nodes: composition$0.Node[] | null, edges: composition$0.Edge[] | null, attrs: composition$0.AttributeDef[] | null): $CancellablePromise<composition$0.Issue[] | null> {
    return $Call.ByID(2793538229, nodes, edges, attrs);
}

/**
 * Workflows returns every workflow -- seeded examples and user-composed
 * ones alike, all ordinary entries in c.user (see restore's first-run
 * seeding below). No BuiltInWorkflows() call here: once seeded, they're
 * just data, the same industry pattern confirmed in docs/SPEC.md §2.2's
 * Update note (a Zapier template "operates independently... you can edit
 * it like any other Zap" the moment it exists) -- not a protected
 * specimen re-appended on every read.
 */
export function Workflows(): $CancellablePromise<composition$0.Workflow[] | null> {
    return $Call.ByID(1715574698);
}
