// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as reference$0 from "../reference/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as seedorigin$0 from "../seedorigin/models.js";

/**
 * AIProvider is one reusable, named AI endpoint connection. Carries no
 * secret VALUE of its own -- same "the secret itself never lives on
 * the domain value" rule httprequest.HTTPRequest/ADR-0007 already
 * established. A BYO endpoint's API key (or Anthropic's x-api-key)
 * lives in the secret store and this entity names it (KeyRef, goal
 * 0306); empty for a local endpoint that needs no credential at all.
 */
export interface AIProvider {
    "ID": string;
    "Label": string;
    "Kind": Kind;
    "BaseURL": string;
    "Model": string;

    /**
     * KeyRef names this endpoint's API key in the secret store (goal
     * 0306) -- a reference (internal/domain/vaultref), never a value.
     * Empty means the endpoint needs no credential, which is the whole
     * configuration for a local one.
     */
    "KeyRef": string;

    /**
     * BuiltIn marks a seeded example AIProvider (BuiltIn() below) --
     * purely informational, same as mcpserver.MCPServer.BuiltIn/
     * decision.Decision.BuiltIn/list.List.BuiltIn: drives a "built-in"
     * badge only, never gates Edit/Delete.
     */
    "BuiltIn": boolean;

    /**
     * CreatedAt/UpdatedAt are system-managed audit timestamps (SPEC.md
     * §3.2.2's reserved-column pattern), stamped server-side at every
     * persisted mutation (ConfigureService), never trusted from the
     * wire. Zero value means pre-timestamp data -- migration-free.
     */
    "CreatedAt": string;
    "UpdatedAt": string;

    /**
     * Seed is this provider's seed provenance (docs/goals/0037) -- zero
     * value means "not of seed origin," migration-free. See
     * composition.Workflow.Seed's doc comment for the full reasoning.
     */
    "Seed": seedorigin$0.Origin;
}

export enum AuthenticationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthenticationNotRequired = "not-required",
    AuthenticationUnknown = "unknown",
    AuthenticationMetadataAuthorized = "metadata-authorized",
    AuthenticationOperationTested = "operation-tested",
    AuthenticationRejected = "rejected",
};

export enum ChangeBlockerCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ChangeBlockerProviderInUse = "provider-in-use",
    ChangeBlockerProviderUseIndeterminate = "provider-use-indeterminate",
    ChangeBlockerProviderOwnershipUnestablished = "provider-ownership-unestablished",
    ChangeBlockerProviderCheckUnavailable = "provider-check-unavailable",
};

/**
 * ChangeImpact reports execution evidence separately from authored consumers.
 * RunIDs and WorkflowIDs contain only confirmed provider references; a safety
 * check that cannot prove absence is represented by its blocker code.
 */
export interface ChangeImpact {
    "providerId": string;
    "configRevision": string;
    "runIDs": string[] | null;
    "workflowIDs": string[] | null;
    "mutationAllowed": boolean;
    "blockerCodes": ChangeBlockerCode[] | null;
}

export enum CheckStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CheckNotStarted = "not-started",
    CheckAwaitingApproval = "awaiting-approval",
    CheckChecking = "checking",
    CheckCancelled = "cancelled",
    CheckTimedOut = "timed-out",
    CheckCompleted = "completed",
};

export enum EvidenceSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EvidenceProviderMetadata = "provider-metadata",
    EvidenceSampleTest = "sample-test",
    EvidenceAdapterContract = "adapter-contract",
};

export enum Freshness {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FreshnessNotChecked = "not-checked",
    FreshnessFresh = "fresh",
    FreshnessStale = "stale",
};

export enum ImportMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ImportModeCreate = "create",
    ImportModeReplace = "replace",
};

/**
 * ImportPreview is a compare-and-apply token plus the information needed to
 * review a provider import without resolving a secret or contacting its host.
 */
export interface ImportPreview {
    "providerId": string;
    "mode": ImportMode;
    "expectedRevision": string;
    "current"?: ImportProjection | null;
    "proposed": ImportProjection;
    "references": reference$0.Refs;
    "impact": ChangeImpact;
}

/**
 * ImportProjection is the credential-free subset shown before an import.
 */
export interface ImportProjection {
    "label": string;
    "kind": Kind;
    "endpoint": string;
    "model": string;
    "keyRef": string;
}

export enum InspectionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    InspectionNotChecked = "not-checked",
    InspectionAvailable = "available",
    InspectionUnsupported = "unsupported",
    InspectionFailed = "failed",
};

/**
 * Kind is a provider's wire-protocol family -- a closed, typed choice
 * (execenv.Shell's own "typed choice, not free text" precedent), each
 * value dispatched to its own adapter in internal/adapters/aiclient.
 * Deliberately just two: docs/goals/0031-ai-node-family.md's own
 * research verdict is that every real BYO/local endpoint (Ollama, LM
 * Studio, vLLM, OpenAI itself, Groq, ...) speaks the OpenAI-compatible
 * /v1/chat/completions shape, and Anthropic's Messages API is the one
 * documented exception (its own docs disqualify the OpenAI compat shim
 * for production) -- not an extensible plugin registry, since no third
 * wire shape is known to exist today (CLAUDE.md's "don't build for a
 * decision that doesn't exist yet").
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindOpenAICompat = "openai-compatible",
    KindAnthropic = "anthropic",
};

export interface ModelChoice {
    "id": string;
}

export enum Operation {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OperationText = "text",
    OperationStructured = "structured",
    OperationClassification = "classification",
};

export interface OperationFeature {
    "operation": Operation;
    "support": Support;
    "evidence": EvidenceSource;
    "wireOperation": string;
    "reasonCodes": string[] | null;
    "lastSampleAttempt"?: SampleEvidence | null;
    "lastSampleSuccess"?: SampleEvidence | null;
}

export interface PermissionResult {
    "status": PermissionStatus;
    "source": string;
    "ruleId"?: string;
    "ruleLabel"?: string;
}

export enum PermissionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PermissionUnchecked = "unchecked",
    PermissionAllowed = "allowed",
    PermissionDenied = "denied",
};

/**
 * Report is machine-local evidence about one configured provider revision.
 * It contains neither provider credentials nor raw provider responses and is
 * intentionally absent from configuration export schemas.
 */
export interface Report {
    "providerId": string;
    "checkId": string;
    "configRevision": string;
    "model": string;
    "adapterVersion": number;
    "machineId": string;
    "sessionId": string;
    "checkedAt": string;
    "checkedEndpoint": string;
    "transport": TransportStatus;
    "inspection": InspectionStatus;
    "authentication": AuthenticationStatus;
    "permission": PermissionResult;
    "operations": OperationFeature[] | null;
    "modelChoices": ModelChoice[] | null;
    "modelInventoryComplete": boolean;
    "selectedModelFound"?: boolean | null;
    "reasonCodes": string[] | null;
    "freshness": Freshness;
    "lifecycle": CheckStatus;
}

/**
 * SampleEvidence is operation-scoped evidence produced by an ordinary sample
 * run. The containing OperationFeature supplies the operation identity.
 */
export interface SampleEvidence {
    "runID": string;
    "sampleVersion": string;
    "schemaDigest": string;
    "configRevision": string;
    "checkedAt": string;
    "outcome": SampleOutcome;
    "freshness": Freshness;
    "authentication": AuthenticationStatus;
}

export enum SampleOutcome {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SampleOutcomeSucceeded = "succeeded",
    SampleOutcomeFailed = "failed",
    SampleOutcomeCancelled = "cancelled",
};

/**
 * SamplePreview describes an ordinary, visible workflow prepared for one
 * provider operation. It contains configuration metadata only, never a key or
 * raw provider response.
 */
export interface SamplePreview {
    "workflowID": string;
    "operation": Operation;
    "sampleVersion": string;
    "status": SampleStatus;
    "syntheticInput": string;
    "safeDestination": string;
    "model": string;
    "configRevision": string;
}

export enum SampleStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SampleStatusCreated = "created",
    SampleStatusExisting = "existing",
    SampleStatusModified = "modified",
};

export enum Support {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SupportSupported = "supported",
    SupportUnsupported = "unsupported",
    SupportUnknown = "unknown",
};

export enum TransportStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TransportUnchecked = "unchecked",
    TransportChecking = "checking",
    TransportResponded = "responded",
    TransportUnreachable = "unreachable",
    TransportInvalidConfiguration = "invalid-configuration",
};
